/* Generated by pwa/generate_service_worker.py. */
const CACHE_PREFIX = "pogruzhenie-offline-";
const CACHE_NAME = CACHE_PREFIX + "57655b3b1b6eeb6f";
const PRECACHE_PATHS = [
  "index.html",
  "ui.html",
  "pwa/manifest.webmanifest",
  "pwa/web-bridge.js",
  "pwa/learning-model.js",
  "pwa/offline-learning.js",
  "pwa/icons/apple-touch-icon.png",
  "pwa/icons/icon-192.png",
  "pwa/icons/icon-512.png",
  "pwa/data/glossary.json",
  "pwa/data/course/pre-a1/catalog.json",
  "pwa/data/course/a1/catalog.json",
  "pwa/data/grammar.json",
  "pwa/data/speaking.json",
  "pwa/data/videos.json",
  "seed/channels.json",
  "seed/grammar.json",
  "seed/questions_A1.json",
  "seed/questions_A2.json",
  "seed/questions_B1.json",
  "seed/questions_B2.json",
  "seed/questions_C1.json",
  "seed/texts_A1.json",
  "seed/texts_A2.json",
  "seed/texts_B1.json",
  "seed/texts_B2.json",
  "seed/texts_C1.json",
  "seed/topics.json",
  "pwa/data/texts/0a42edcab91c278f.json",
  "pwa/data/texts/0cea062c2ef72775.json",
  "pwa/data/texts/1dd5af38fa833f4d.json",
  "pwa/data/texts/2367790f4eddb33c.json",
  "pwa/data/texts/3338f2a187061f40.json",
  "pwa/data/texts/4d9c48562b4254d6.json",
  "pwa/data/texts/53a07cafd7adb815.json",
  "pwa/data/texts/5e0654d7265da3eb.json",
  "pwa/data/texts/65ed07e5ab6f1702.json",
  "pwa/data/texts/6c2e17860a712b67.json",
  "pwa/data/texts/75d844994acf2bfc.json",
  "pwa/data/texts/8328ef679010e3aa.json",
  "pwa/data/texts/8745643bae7c71b3.json",
  "pwa/data/texts/d1220831fbd90515.json",
  "pwa/data/texts/df90b65eb94793d6.json"
];
const APP_SHELL = new URL("ui.html", self.registration.scope).href;

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(
        PRECACHE_PATHS.map((path) => new Request(
          new URL(path, self.registration.scope).href, {cache: "reload"}
        ))
      ))
  );
});

// A complete package waits until the page has saved current work and the
// learner explicitly accepts the update. Until then the active worker keeps
// serving one coherent previous cache.
self.addEventListener("message", (event) => {
  if (event.data?.type === "APPLY_UPDATE") event.waitUntil(self.skipWaiting());
});

self.addEventListener("activate", (event) => {
  // Do not claim already open tabs and do not remove their release cache.
  // Each tab stays coherent until its user-approved reload; new navigations
  // use this worker and this CACHE_NAME. Retaining the previous cache also
  // keeps the documented rollback path available.
  event.waitUntil(Promise.resolve());
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Serve the HTML and modules from the same installed release. Only the
  // allowlisted package is cached; other requests can use the network without
  // failing just because iPhone storage cannot accept another cache write.
  event.respondWith(
    (async () => {
      try {
        const cache = await caches.open(CACHE_NAME);
        const cached = (await cache.match(request)) ||
          (request.mode === "navigate" ? await cache.match(APP_SHELL) : null);
        if (cached) return cached;
      } catch (error) {
        console.warn("Pogruzhenie offline cache unavailable:", error?.name || "StorageError");
      }
      // Network failures must remain failures, not an empty success response.
      return fetch(request);
    })()
  );
});
